### ISSUE TITLE
Caso 18 - El sistema de vida-background funciona una sóla única vez

### ISSUE THREAD

**Issue by AndresCarnicero** [Proyectos1-FDI-UCM/c1920-Grupo02#18]
#CriticalBug
**Descripción** 
El fondo cambia cuando pierdes vida y se entiende perfectamente. Sin embargo esto sólo funciona durante la primera partida que realices al abrir el juego hasta que mueres por primera vez.

Importante esto de “hasta que mueres”, porque, como se ve en el vídeo, si en la primera partida, te sales del nivel sin haber muerto, cuando juegues otro nivel, todavía funciona el sistema de vida-background.

También me ocurrió un fallo puntual en el que el fondo pasó de estar azul a rojo sin pasar por el resto de colores (creo que porque no le dió tiempo a actualizarse debido a la gran velocidad con la que perdí vida) de todas formas se ve en el vídeo.

Lo esperable era que funcionase en en cada intento de cada nivel.

**Pasos**
Paso 1. Abrir el juego y seleccionar cualquier nivel
Paso 2. Hacer un primer intento perdiendo vida (no llegar a morir)
Paso 3. Cambiar de nivel y comprobar que sigue funcionando el sistema
Paso 4. Morir en cualquier nivel
Paso 5. Comprobar en ese nivel que ahora el sistema no funciona
Paso 6. Salir, elegir otro nivel y ver que tampoco funciona.
Paso 7. Salir completamente del juego y volver a ver en cualquier nivel que el sistema vuelve a funcionar.

**Vídeo**
https://youtu.be/2H0OlNpaBKE

**Comment by samuebla** [comment]
Corregido
