### ISSUE TITLE
Case 19 - Las plataformas de descenso permiten volver a saltar una vez has descendido

### ISSUE THREAD

**Issue by AndresCarnicero** [Proyectos1-FDI-UCM/c1920-Grupo02#19]
#MinorBug
**Descripción**
Si pulsas el botón de descender en una de esas plataformas, el jugador cae. Sin embargo, si antes de que la pastilla atraviese completamente la plataforma le vuelves a dar a saltar, la pastilla vuelve a hacerlo cuando en teoría no debería, una vez que pulsas hacia abajo no puedes volver a ascender.
**Pasos**
Paso 1. Ir a cualquier nivel con plataformas de ese estilo
Paso 2. Subirse a una plataforma 
Paso 3. Dejarse caer dando al botón de descender y antes de atravesar la plataforma volver a saltar
**Vídeo**
https://youtu.be/FY7s4zsRc8w

**Comment by samuebla** [comment]
El jugador puede realizar un salto tras caerse de cualquier plataforma o suelo, por lo que no consideramos esto como un Bug.
