### ISSUE TITLE
Caso 2-Puedes salir volando de las plataformas

### ISSUE THREAD

**Issue by oskar200130** [Proyectos1-FDI-UCM/c1920-Grupo02#2]
Descripción: La pastilla puede salir volando si saltas cuando estás atravesando la plataforma.
Pasos:
1-Colocate encima de una plataforma
2-Pulsa hacia abajo para atravesarla
3-Cuando la pastilla esté atravesando la plataforma pulsa saltar
Enlace:
https://youtu.be/if24xVPwQJI

**Comment by samuebla** [comment]
Hemos disminuido su frecuencia de aparición pero no hemos sido capaces de disolverlo al completo
