### ISSUE TITLE
Caso 20 - Se puede cambiar la dirección de golpeo a la mitad de la animación

### ISSUE THREAD

**Issue by AndresCarnicero** [Proyectos1-FDI-UCM/c1920-Grupo02#20]
#MinorBug
**Descripción**
Con cualquier pastilla, si atacas (ataque estándar) y mientras dure la animación de ataque cambias la dirección, la pastilla se teletransporta en la otra dirección de forma muy brusca y acaba la animación.
Este cambio de dirección también causa daño a los enemigos
El resultado esperado debería ser que una vez ataques no pudieses cambiar de dirección
**Pasos** 
Paso 1. Seleccionar cualquier nivel
Paso 2. Atacar a izquierda
Paso 3. A mitad de animación cambiar la dirección a la derecha (no atacar otra vez, sólo cambiar la dirección).
**Vídeo**
https://www.youtube.com/watch?v=iTlXIXn1dqM

**Comment by samuebla** [comment]
No consideramos que esto sea un bug, creemos que es una Feature
