### ISSUE TITLE
Caso 23 - Cuando tocas la Gran Tenia, la pastilla comienza a hacer popping

### ISSUE THREAD

**Issue by AndresCarnicero** [Proyectos1-FDI-UCM/c1920-Grupo02#23]
#CriticalBug
**Descripción**
Al tocar la Gran Tenia, la pastilla comienza a hacer cosas muy extrañas, se teletransporta, salta y petardea mucho, se hace injugable.
**Pasos** 
Paso 1. Ir al nivel de la Gran Tenia
Paso 2. Tocar a la Gran Tenia desde cualquier posición en cualquier estado
Paso 3. Ver el fallo gráfico
**Vídeo**
https://youtu.be/3wIV_qPiHT8

**Comment by samuebla** [comment]
El movimiento tan brusco de la cámara es intencionado, el objetivo es que cuando toques a la Tenia la cámara se mueva mucho y te "asuste", ahora hemos añadido un ruido para dar a entender que el movimiento de la cámara es adrede
