### ISSUE TITLE
Caso 24 - En ocasiones, los enemigos se quedan congelados al atacarlos 

### ISSUE THREAD

**Issue by AndresCarnicero** [Proyectos1-FDI-UCM/c1920-Grupo02#24]
#MinorBug
#5 Hago referencia al caso 5, es más información sobre ese bug
**Descripción**
Este bug me ha ocurrido varias veces pero no soy capaz de recrearlo con exactitud, por suerte he conseguido capturar varios clips.
De lo que he podido deducir es, que atacando a los enemigos disparando con la pastilla blanca, se pueden llegar a quedar parados varios segundos o de forma indefinida,
https://youtu.be/FH4sVHzdjGg

**Comment by samuebla** [comment]
Has puesto el video en privado, cámbialo cuando puedas por favor
