### ISSUE TITLE
Caso 3-La pastilla entra dentro de los muros

### ISSUE THREAD

**Issue by oskar200130** [Proyectos1-FDI-UCM/c1920-Grupo02#3]
Descripción: Cuando haces el ataque contra una pared la pastilla da la impresión de estar atravesando la pared
Pasos:
1- Colócate al lado de cualquier pared
2- Realiza el golpe hacia la pared
Captura:
![Anotación 2020-05-30 182353](https://user-images.githubusercontent.com/62761404/83363656-6223e780-a39b-11ea-80b4-a91a7b11941d.png)

**Comment by samuebla** [comment]
Consideramos este comportamiento como apropiado para un juego de plataformas, debido a que esta situación ocurre en la gran mayoría de Juegos plataformeros
