### ISSUE TITLE
Caso 4-Invulnerable quieto.

### ISSUE THREAD

**Issue by albemu07** [Proyectos1-FDI-UCM/c1920-Grupo02#4]
Descripción: En objetos como el ácido o el coágulo, si permaneces quieto encima de ellos, solo recibes daño la primera vez.
Pasos: 
1.- situarse encima del ácido o un coágulo.
2.-Quedarse quieto y observar la vida.

**Comment by samuebla** [comment]
Ya está corregido, ahora te hace daño por segundo
