### ISSUE TITLE
Caso 5- Tenia (no boss) se queda atascada.

### ISSUE THREAD

**Issue by albemu07** [Proyectos1-FDI-UCM/c1920-Grupo02#5]
Descripción: una tenia situada en el nivel, después de la segunda puerta, se queda atascada encima de la ácido hacia la izquierda y no puede alcanzarte.
Pasos:
1- Ir en el nivel uno hasta la segunda puerta.
2.- Situarse entre el ácido y la plataforma flotante.
3.- Observar como la tenia no puede alcanzarte

**Comment by samuebla** [comment]
Corregido
