### ISSUE TITLE
Caso 7 - Disparo en salto no coincide con la animación

### ISSUE THREAD

**Issue by SergioJAlfonso** [Proyectos1-FDI-UCM/c1920-Grupo02#7]
**Descripción**
Al caer o al saltar mientras se dispara, el disparo no se coordina con la animación.

**Pasos**
1. Entrar en cualquier nivel.
2. Disparar en el momento en el que se salta.
3. Disparar en caída.

**Captura de pantalla o vídeo**
https://youtu.be/UsjuLbgUR6w

**Comment by samuebla** [comment]
Ahora le hemos puesto un ligero retardo para que corresponda con la animación.
