### ISSUE TITLE
Caso 9 - Muerte instantánea durante la pelea contra el Gran Coágulo

### ISSUE THREAD

**Issue by SergioJAlfonso** [Proyectos1-FDI-UCM/c1920-Grupo02#9]
**Descripción**
Al enfrentarse al Gran Coágulo, la píldora muere instantáneamente cuando aparecen
los enemigos que recorren la pantalla desde el suelo hasta el techo, aunque no entre
en colisión con ellos.

**Pasos**
1. Entrar en el nivel del Gran Coágulo.
2. Destruir el primer coágulo.
3. Esperar hasta que aparezcan los enemigos que se mueven desde el suelo hasta
el techo.
4. Posicionarse en la plataforma que se indica en el vídeo.

**Captura de pantalla o vídeo**
https://youtu.be/im69PsmHTUM

**Comment by mihern07** [comment]
Este comportamiento no es un error y es intencionado. En las nuevas versiones del juego se incluye una animación de explosión que justifica esta muerte instantánea. Esto ocurre no por quedarse quieto sino al pasar unos segundos y no haber matado a los coágulos pequeños. Esta mecánica se encontraba descrita en el plan de pruebas.
